### PR TITLE
12_jyox007

### PR DESCRIPTION
**Pull request by jyoti-u**
Here is my solution for issue  #12

### CODE REVIEW

**Comment by jyox007** [comment]
12_jyox007 is the final submission for this issue.

**Comment by jyox007** [comment]
11_jyox007 is the solution for issue #11 .

**Comment by jyoti-u** [comment]
In my last file, I have added the solution for issue # 2. I am not able to submit is separately, so I am adding here. It contains solutions for issue #12, issue #11 and issue #2 .

**Comment by teonbrooks** [comment]
@jyox007 thanks for the update. we are only looking for one issue to be solved in the pr. could you update your pr to include just the one you would like for us to evaluate.

**Comment by jyoti-u** [comment]
@teonbrooks I am okay if you chose any one issue out of 3 in my pr request.

**Comment by teonbrooks** [comment]
@jyox007 it will be much easier for us in evaluating if you select the exemplar issue to highlight in your pr. we have many submissions and we announced in the gitter that it is the responsibility of the submitter to choose otherwise, we will blindly and randomly select one.

**Comment by jyoti-u** [comment]
@teonbrooks its okay you can select any one randomly from the 3 , all three are equally correct. Its already very meshy and I dont want to make any last minute changes. I have faced enough trouble because of github and I dont want to take any risk now.

**Pull request merged**
